### ISSUE TITLE
This repository is over its data quota.

### ISSUE THREAD

**Issue by antichristHater** [abdur75648/End-To-End-Urdu-OCR-WebApp#2]
Getting `This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.` error while trying to pull the repository.

Also the pretrained model from the original repository (https://github.com/abdur75648/UTRNet-High-Resolution-Urdu-Text-Recognition, UTRNet-Large) raises shape mismatch error: ```raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
        Missing key(s) in state_dict:```

Can you upload the weights on a separate cloud service like Google Drive?

**Comment by humada05** [comment]
+1 seeing the same error when I attempt to run the web app locally

**Comment by abdur75648** [comment]
@humada05 @antichristHater 
I have removed the model weights from Git LFS as the repository exceeded its data quota for LFS bandwidth. You can still access the weights and test samples by downloading them from the [Hugging Face repository](https://huggingface.co/spaces/abdur75648/UrduOCR-UTRNet) using the provided `download_files.sh` script.

Alternatively, you can clone the Hugging Face repository directly by following these steps:

1. Ensure you have [Git LFS installed](https://git-lfs.com):
   ```bash
   git lfs install
   ```

2. Clone the repository:
   ```bash
   git clone https://huggingface.co/spaces/abdur75648/UrduOCR-UTRNet
   ```

Let me know if you encounter any issues!
